import type { PilotRun, PilotState } from '../data/types';

type Props = { pilot: PilotRun; state: PilotState; onReset: () => void };

export function ExportPanel({ pilot, state, onReset }: Props) {
  function exportJSON() {
    const blob = new Blob([JSON.stringify({ pilot: pilot.id, title: pilot.title, state }, null, 2)], { type: 'application/json' });
    download(blob, `${pilot.id.toLowerCase()}-state.json`);
  }

  function exportMarkdown() {
    const lines: string[] = [
      `# ${pilot.title}`,
      ``,
      `**Scenario:** ${pilot.scenario}`,
      `**Exported:** ${new Date().toLocaleString('en-AU')}`,
      ``,
      `---`,
      ``,
    ];

    for (const stage of pilot.stages) {
      const entry = state.entries[stage.id];
      if (!entry?.output) continue;
      lines.push(`## ${stage.label}`);
      lines.push(``);
      lines.push(entry.output.content);
      lines.push(``);
      lines.push(`---`);
      lines.push(``);
    }

    lines.push(`*Generated by VALOUR™ Pilot Console · © 2026 ZenCloud Global Consultants*`);

    const blob = new Blob([lines.join('\n')], { type: 'text/markdown' });
    download(blob, `${pilot.id.toLowerCase()}-report.md`);
  }

  function download(blob: Blob, name: string) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = name; a.click();
    URL.revokeObjectURL(url);
  }

  const completedCount = Object.values(state.entries).filter(e => e.output).length;
  const totalStages = pilot.stages.length;

  return (
    <div className="export-panel">
      <div className="export-panel-header">
        <div className="info-card-label">Pilot actions</div>
        <span className="export-progress">{completedCount}/{totalStages} stages with output</span>
      </div>
      <div className="export-actions">
        <button className="btn btn-ghost export-btn" onClick={exportJSON} disabled={completedCount === 0} title="Download state as JSON">
          ↓ JSON
        </button>
        <button className="btn btn-ghost export-btn" onClick={exportMarkdown} disabled={completedCount === 0} title="Download report as Markdown">
          ↓ Markdown
        </button>
        <button
          className="btn export-btn export-btn-reset"
          onClick={() => { if (confirm('Reset all pilot state? This cannot be undone.')) onReset(); }}
          title="Reset all pilot state"
        >
          Reset pilot
        </button>
      </div>
    </div>
  );
}
