import type { PatternSummary, PilotRun, PilotState } from '../data/types';
import { simpleMarkdown } from './StageWorkspace';

type Props = {
  pilot: PilotRun;
  liveContent?: string;
  liveState?: PilotState;
  onBack: () => void;
  onReset: () => void;
  onStartNew: () => void;
};

export function PatternPage({ pilot, liveContent, liveState, onBack, onReset, onStartNew }: Props) {
  const { pattern } = pilot;
  const pilotTitle = pilot.title.replace(': ', ' · ');
  const hasLive = !!liveContent;

  function download(blob: Blob, name: string) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = name; a.click();
    URL.revokeObjectURL(url);
  }

  function fallbackText(p: PatternSummary): string {
    return [
      `Primary Pattern: ${p.primaryPattern}`,
      `Starting Challenge: ${p.startingChallenge}`,
      `Main Improvement: ${p.mainImprovement}`,
      `Primary Strength: ${p.primaryStrength}`,
      `Primary Risk: ${p.primaryRisk}`,
      `Next Focus: ${p.nextFocus}`,
      `Useful Language: ${p.usefulLanguage.join('; ')}`,
      `Usefulness Score: ${p.usefulnessScore}/10`,
    ].join('\n');
  }

  function handleCopy() {
    const text = liveContent ?? fallbackText(pattern);
    navigator.clipboard.writeText(text).catch(() => {});
  }

  function handleExportMarkdown() {
    const body = liveContent ?? fallbackText(pattern);
    const lines = [
      `# ${pilotTitle}`,
      `**Scenario:** ${pilot.scenario}`,
      `**Generated:** ${new Date().toLocaleString('en-AU')}`,
      '',
      body,
      '',
      '*Generated by VALOUR\u2122 · © 2026 The OrdoAnimi Group*',
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/markdown' });
    download(blob, `${pilot.id.toLowerCase()}-pattern-report.md`);
  }

  function handleExportJSON() {
    const payload = {
      pilot: pilot.id,
      title: pilotTitle,
      scenario: pilot.scenario,
      generatedAt: new Date().toISOString(),
      pattern: pilot.pattern,
      liveReport: liveContent ?? null,
      state: liveState ?? null,
    };
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
    download(blob, `${pilot.id.toLowerCase()}-pattern-report.json`);
  }

  function handleEmail() {
    const subject = encodeURIComponent(`VALOUR\u2122 Pattern Report — ${pilotTitle}`);
    const snippet = (liveContent ?? fallbackText(pattern)).slice(0, 1200);
    const body = encodeURIComponent(`${snippet}\n\n[Full report generated by VALOUR\u2122 Pilot Console]`);
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  }

  function handleReset() {
    if (confirm('Reset all pilot state? This cannot be undone.')) onReset();
  }

  return (
    <div className="pattern-page">

      <nav className="pattern-nav no-print">
        <button className="btn btn-ghost pattern-back" onClick={onBack}>← Console</button>
        <span className="landing-logo">VALOUR&trade;</span>
        <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: '8px' }}>
          {hasLive && (
            <span className="pattern-live-badge">✦ AI generated</span>
          )}
          <span className="pattern-nav-title">Pattern Report</span>
        </div>
      </nav>

      <div className="pattern-hero">
        <div className="landing-eyebrow">{pilotTitle}</div>
        <h1 className="pattern-heading">Leadership Pattern Report</h1>
        {!hasLive && (
          <p style={{ color: 'var(--text-dim)', fontSize: '13px', marginTop: '8px' }}>
            Generate Stage 07 (Pattern Summary) in the console to produce a personalised AI report.
          </p>
        )}
      </div>

      {/* Live AI-generated content */}
      {hasLive && (
        <div className="pattern-live-content markdown-content"
             dangerouslySetInnerHTML={{ __html: simpleMarkdown(liveContent!) }} />
      )}

      {/* Static seed data (always shown as fallback or supplement) */}
      {!hasLive && (
        <div className="pattern-grid">

          <div className="pattern-card pattern-card-primary">
            <div className="pattern-card-label">Primary pattern</div>
            <div className="pattern-card-value">{pattern.primaryPattern}</div>
          </div>

          <div className="pattern-card">
            <div className="pattern-card-label">Usefulness score</div>
            <div className="pattern-score">{pattern.usefulnessScore}<span className="pattern-score-max">/10</span></div>
          </div>

          <div className="pattern-card pattern-card-wide">
            <div className="pattern-card-label">Starting challenge</div>
            <p className="pattern-card-body">{pattern.startingChallenge}</p>
          </div>

          <div className="pattern-card pattern-card-wide">
            <div className="pattern-card-label">Main improvement</div>
            <p className="pattern-card-body pattern-positive">{pattern.mainImprovement}</p>
          </div>

          <div className="pattern-card">
            <div className="pattern-card-label">Primary strength</div>
            <p className="pattern-card-body">{pattern.primaryStrength}</p>
          </div>

          <div className="pattern-card">
            <div className="pattern-card-label">Primary risk</div>
            <p className="pattern-card-body pattern-risk">{pattern.primaryRisk}</p>
          </div>

          <div className="pattern-card pattern-card-wide pattern-card-focus">
            <div className="pattern-card-label">Next focus</div>
            <p className="pattern-card-value">{pattern.nextFocus}</p>
          </div>

          <div className="pattern-card pattern-card-full">
            <div className="pattern-card-label">Useful language to retain</div>
            <div className="pattern-language-list">
              {pattern.usefulLanguage.map((line, i) => (
                <div key={i} className="pattern-language-item">
                  <span className="pattern-language-quote">"</span>
                  <span>{line}</span>
                  <span className="pattern-language-quote">"</span>
                </div>
              ))}
            </div>
          </div>

        </div>
      )}

      {/* Report action bar */}
      <div className="pattern-actions no-print">
        <div className="pattern-actions-label">Report actions</div>
        <div className="pattern-actions-grid">
          <button className="pattern-action-btn" onClick={handleCopy}>Copy report</button>
          <button className="pattern-action-btn" onClick={handleExportMarkdown}>↓ Markdown</button>
          <button className="pattern-action-btn" onClick={handleExportJSON}>↓ JSON</button>
          <button className="pattern-action-btn" onClick={() => window.print()}>Print / PDF</button>
          <button className="pattern-action-btn" onClick={handleEmail}>Email to myself</button>
          <button className="pattern-action-btn pattern-action-start" onClick={onStartNew}>Start another pilot</button>
          <button className="pattern-action-btn pattern-action-reset" onClick={handleReset}>Reset pilot</button>
        </div>
      </div>

    </div>
  );
}
